// GENERATED BY CODE! DO NOT MODIFY!
namespace Watermelon
{
	public partial class PrefsSettings
	{
		public enum Key
		{
			Vibration = 0,
			Volume = 1,
			CurrentLevelID = 2,
			ActualLevelID = 3,
			CarSkinID = 4,
			EnvironmentSkinID = 5,
			CoinsCountID = 6,
			KeysCountID = 7,
			LastKeyPickedLevelID = 8,
		}
	}
}